[profile.default]
solc_version = "0.8.26"
auto_detect_solc = false
evm_version = "shanghai"
src = "src"
out = "out"
libs = ["lib"]
ffi = true
gas_reports = ["*"]
optimizer = true
optimizer_runs = 1_000

[profile.default.fuzz]
runs = 1024

[fmt]
line_length = 80

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
SEPOLIA = "${SEPOLIA_RPC_URL}"
ETH = "${ETH_RPC_URL}"
OPT = "${OPT_RPC_URL}"
BSC = "${BSC_RPC_URL}"
MATIC = "${MATIC_RPC}"
ZKSYNC = "${ZKSYNC_RPC}"
ARB = "${ARB_RPC}"
BASE = "${BASE_RPC}"
SCROLL_RPC = "${SCROLL}"
LINEA = "${LINEA_RPC}"
OPBNB = "${OPBNB_RPC}"
ARBNOVA = "${ARBNOVA_RPC}"
MATICZK = "${MATICZK_RPC}"
AVA = "${AVA_RPC}"
